#!/usr/bin/env python

from piksi_pps_sync.evaluation import *

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Correlate IMU data.')
    parser.add_argument('bag', nargs=1, help='The path to the bag file containing the IMU measurements.')
    parser.add_argument('piksi', nargs=1, help='The Piksi IMU topic.')
    parser.add_argument('external', nargs=1, help='The external IMU topic.')

    args = parser.parse_args()

    omega_piksi, times_piksi, omega_external, times_external = loadMessages(args.bag[0], args.piksi[0], args.external[0])

    t_off = computeTimeOffset(omega_piksi, times_piksi, omega_external, times_external)

    plotCorrelation(omega_piksi, times_piksi, omega_external, times_external, t_off)
