# MSG BASELINE NED — 0x020C — 524

std_msgs/UInt32                       tow        # GPS Time of Week
piksi_multi_msgs/PointNed             coordinate # Baseline coordinate in NED frame.
piksi_multi_msgs/AccuracyTangentPlane accuracy   # Horizontal and vertical standard deviation
std_msgs/UInt8                        n_sats     # Number of satellites used in solution
piksi_multi_msgs/FixMode              fix_mode   # Fix mode
