std_msgs/Float32 n_n # Estimated variance of northing
std_msgs/Float32 n_e # Estimated covariance of northing and easting
std_msgs/Float32 n_d # Estimated covariance of northing and downward measurement
std_msgs/Float32 e_e # Estimated variance of easting
std_msgs/Float32 e_d # Estimated covariance of easting and downward measurement
std_msgs/Float32 d_d # Estimated variance of downward measurement
