# MSG HEARTBEAT — 0xFFFF — 65535

std_msgs/Bool  system_error             # System error flag
std_msgs/Bool  io_error                 # IO error flag
std_msgs/Bool  swift_nap_error          # SwiftNAP error flag
std_msgs/UInt8 sbp_minor_version        # SBP minor protocol version number
std_msgs/UInt8 sbp_major_version        # SBP major protocol version number
std_msgs/Bool  short_detected           # External antenna short flag
std_msgs/Bool  external_antenna_present # External antenna present flag
