# MSG POS LLH COV — 0x0211 — 529

uint32                 tow              # GPS Time of Week
PointWgs84             coordinate_wgs84 # WGS84 coordinate
CovTangentNed          cov              # Estimated covariance of WGS84 coordinate
uint8                  n_sats           # Number of satellites used in solution
FixMode                fix_mode         # Fix mode
InertialNavigationMode ins_mode         # Inertial navigation mode
