# MSG VEL ECEF COV — 0x0215 — 533

std_msgs/UInt32                         tow           # GPS Time of Week
piksi_multi_msgs/VectorEcef             velocity      # Velocity ECEF coordinates
piksi_multi_msgs/CovCartesian           cov           # Estimated covariance
std_msgs/UInt8                          n_sats        # Number of satellites used in solution
piksi_multi_msgs/VelocityMode           velocity_mode # Velocity mode values
piksi_multi_msgs/InertialNavigationMode ins_mode      # Inertial navigation mode
