# MSG VEL NED — 0x020E — 526

uint32                 tow           # GPS Time of Week
VectorNed              velocity_ned  # Velocity in NED frame.
AccuracyTangentPlane   accuracy      # Horizontal and vertical standard deviation
uint8                  n_sats        # Number of satellites used in solution
VelocityMode           velocity_mode # Velocity mode values
InertialNavigationMode ins_mode      # Inertial navigation mode
