# MSG VEL NED COV — 0x0212 — 530

uint32                 tow           # GPS Time of Week
VectorNed              velocity_ned  # Velocity in NED frame.
CovTangentNed          cov           # Estimated covariance
uint8                  n_sats        # Number of satellites used in solution
VelocityMode           velocity_mode # Velocity mode values
InertialNavigationMode ins_mode      # Inertial navigation mode
